# Generated by Django 2.2.5 on 2019-09-17 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0002_bankaccount_party'),
        ('challans', '0002_auto_20190917_0547'),
        ('parties', '0002_party_rate_group'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('extra_info', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_accounts.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_full_amount', models.BooleanField()),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('account_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.AccountTransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_choice', models.CharField(choices=[('CS', 'Cash'), ('AC', 'Account'), ('AL', 'Account Less')], max_length=2)),
                ('gateway_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_payed', models.BooleanField(default=False)),
                ('payed_on', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('extra_info', models.TextField(blank=True)),
                ('challan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challans.Challan')),
                ('gateway_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
