# Generated by Django 2.2.5 on 2019-09-27 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('challans', '0001_initial'),
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('FL', 'Full Payment'), ('AL', 'Account Less')], max_length=2)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payed_on', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('extra_info', models.TextField(blank=True)),
                ('challan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challans.Challan')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_full_amount', models.BooleanField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('payed_on', models.DateTimeField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('payed_on', models.DateTimeField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_accounts.BankAccount')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
            ],
        ),
    ]
