# Generated by Django 2.2.6 on 2019-10-18 18:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='deducted_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9),
        ),
    ]
