# Generated by Django 2.2.5 on 2019-09-26 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='gateway_choice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_payed',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='account_transaction',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='remaining_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('FL', 'Full Payment'), ('AL', 'Account Less')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.Payment'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('extra_info', models.TextField(blank=True)),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Pay')),
            ],
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='pay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.Pay'),
            preserve_default=False,
        ),
    ]
