# Generated by Django 2.2.5 on 2019-09-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashTransaction',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='gateway_id',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='gateway_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_choice',
            field=models.CharField(choices=[('CS', 'Cash'), ('AC', 'Account'), ('AL', 'Account Less')], default='CS', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='account_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.AccountTransaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
