# Generated by Django 2.2.5 on 2019-09-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('FL', 'Full Payment'), ('AL', 'Account Less')], max_length=2, null=True),
        ),
    ]
