# Generated by Django 2.2.6 on 2019-10-30 16:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
    ]
