# Generated by Django 2.2.5 on 2019-09-26 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190926_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='payed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='payed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2),
        ),
        migrations.AddField(
            model_name='pay',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2),
        ),
    ]
