# Generated by Django 2.2.5 on 2019-09-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190927_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('DP', 'Direct Payment'), ('AL', 'Account Less')], max_length=2, null=True),
        ),
    ]
