# Generated by Django 2.2.7 on 2019-11-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20191021_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='actr_no',
            field=models.CharField(default='KGP', max_length=7, verbose_name='Payment No'),
        ),
    ]
