# Generated by Django 2.2.6 on 2019-10-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_wallettransaction_previous_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
