# Generated by Django 2.2.6 on 2019-10-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20191018_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpayment',
            name='gateway',
            field=models.CharField(choices=[('AD', 'Adjusted'), ('WL', 'Wallet'), ('CS', 'Cash')], default='AD', max_length=2),
            preserve_default=False,
        ),
    ]
