# Generated by Django 2.2.7 on 2019-11-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_accounttransaction_actr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='serial_no',
            field=models.CharField(blank=tuple, max_length=7, null=True, verbose_name='PY Serial No'),
        ),
    ]
