# Generated by Django 2.2.5 on 2019-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20191002_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='unique_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
