# Generated by Django 2.2.5 on 2019-10-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_accounttransaction_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='unique_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
