# Generated by Django 2.2.5 on 2019-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20191002_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('DP', 'Direct Payment'), ('AL', 'Account Less')], max_length=2, null=True),
        ),
    ]
