# Generated by Django 2.2.5 on 2019-10-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20191005_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
