# Generated by Django 2.2.5 on 2019-09-17 05:47

import challans.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway_choice', models.CharField(choices=[('CS', 'Cash'), ('AC', 'Account'), ('AL', 'Account Less')], max_length=2)),
                ('is_payed', models.BooleanField(default=False)),
                ('challan_no', models.CharField(default=challans.models.challan_no_generator, max_length=32, unique=True)),
                ('weights_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('is_published', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('extra_info', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_weight', models.FloatField(default=0.0)),
                ('total_weight', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challans.Challan')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material')),
            ],
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challans.Weight')),
            ],
            options={
                'verbose_name_plural': 'Weight Entries',
            },
        ),
    ]
