# Generated by Django 2.2.5 on 2019-09-09 05:31

import challans.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_material_is_active'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_id', models.CharField(max_length=32, unique=True)),
                ('weights_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('extra_charges', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('extra_info', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Party')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_counts', models.CharField(default='', max_length=254, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('total_weight', models.FloatField(validators=[challans.validators.validate_positive_float])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challans.Challan')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material')),
            ],
        ),
    ]
