# Generated by Django 2.2.5 on 2019-09-11 05:19

import challans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_is_active'),
        ('challans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challan',
            name='challan_id',
        ),
        migrations.AddField(
            model_name='challan',
            name='challan_no',
            field=models.CharField(default=challans.models.challan_no_generator, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challan',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='challan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='challan',
            name='weights_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together={('challan', 'material')},
        ),
    ]
