# Generated by Django 2.2.6 on 2019-10-19 23:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='round_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(limit_value=-10), django.core.validators.MaxValueValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='challan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
    ]
