# Generated by Django 2.2.5 on 2019-09-27 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('challans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Party'),
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together={('challan', 'material')},
        ),
    ]
