# Generated by Django 2.2.6 on 2019-10-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='stock_weight',
        ),
    ]
