# Generated by Django 2.2.6 on 2019-10-22 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0002_auto_20191019_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='stock_weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
