# Generated by Django 2.2.5 on 2019-09-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0002_auto_20190917_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
