# Generated by Django 2.2.5 on 2019-09-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0002_auto_20190911_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='generated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
