# Generated by Django 2.2.6 on 2019-10-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0002_auto_20191015_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
