# Generated by Django 2.2.5 on 2019-09-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0002_auto_20190927_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challan',
            name='is_entry_done',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='is_payed',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='published_on',
        ),
        migrations.AddField(
            model_name='challan',
            name='status',
            field=models.CharField(default='CR', max_length=2),
        ),
    ]
