# Generated by Django 2.2.6 on 2019-10-18 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0002_auto_20191018_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportweight',
            name='weight_count',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
