# Generated by Django 2.2.6 on 2019-10-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0003_auto_20191018_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportweight',
            name='weight_count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
