# Generated by Django 2.2.6 on 2019-10-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0003_auto_20191017_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challan',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='updated_on',
        ),
    ]
