# Generated by Django 2.2.5 on 2019-09-11 05:46

import challans.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0003_challan_generated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='weight',
            name='total_weight',
            field=models.FloatField(default=0, validators=[challans.validators.validate_positive_float]),
        ),
    ]
