# Generated by Django 2.2.5 on 2019-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0003_auto_20190930_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='vehicle_details',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
