# Generated by Django 2.2.5 on 2019-09-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0003_weight_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='is_entry_done',
            field=models.BooleanField(default=False),
        ),
    ]
