# Generated by Django 2.2.6 on 2019-10-17 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0004_auto_20191017_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challan',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
