# Generated by Django 2.2.5 on 2019-09-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0004_auto_20190911_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
