# Generated by Django 2.2.5 on 2019-10-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0004_challan_vehicle_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2),
        ),
        migrations.AlterField(
            model_name='weight',
            name='report_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
