# Generated by Django 2.2.6 on 2019-10-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0004_auto_20191018_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportweight',
            name='weight_count',
            field=models.FloatField(default=0.0),
        ),
    ]
