# Generated by Django 2.2.5 on 2019-09-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0005_weight_rate_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='challan',
            name='payment_gateway_type',
            field=models.CharField(choices=[('CS', 'Cash'), ('AC', 'Account'), ('AL', 'Account Less')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
