# Generated by Django 2.2.6 on 2019-10-17 19:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0005_auto_20191017_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='round_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='challan',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Kata Charges'),
        ),
    ]
