# Generated by Django 2.2.5 on 2019-10-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0005_auto_20191004_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challan',
            name='status',
        ),
        migrations.AddField(
            model_name='challan',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challan',
            name='is_entries_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challan',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challan',
            name='is_reports_done',
            field=models.BooleanField(default=False),
        ),
    ]
