# Generated by Django 2.2.5 on 2019-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0006_auto_20191005_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
