# Generated by Django 2.2.5 on 2019-09-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0006_auto_20190913_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='is_payed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
