# Generated by Django 2.2.5 on 2019-10-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0008_challan_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challan',
            name='is_done',
        ),
        migrations.AddField(
            model_name='challan',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2),
        ),
    ]
