# Generated by Django 2.2.5 on 2019-10-08 00:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0009_auto_20191007_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_count', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('report_type', models.CharField(choices=[('RP', 'Report'), ('RT', 'Return')], max_length=2)),
                ('reported_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challans.Weight')),
            ],
        ),
    ]
