# Generated by Django 2.2.5 on 2019-10-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0010_reportweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='report_weight',
        ),
        migrations.AddField(
            model_name='reportweight',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2),
        ),
    ]
