# Generated by Django 2.2.5 on 2019-10-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0012_challan_is_rates_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_no',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='reportweight',
            name='weight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challans.Weight'),
        ),
    ]
