# Generated by Django 2.2.6 on 2019-10-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletadvance',
            name='gateway_id',
        ),
        migrations.RemoveField(
            model_name='walletadvance',
            name='gateway_type',
        ),
        migrations.AddField(
            model_name='walletadvance',
            name='gateway',
            field=models.CharField(choices=[('CS', 'Cash'), ('AC', 'Account'), ('IP', 'In Payment')], default='CS', max_length=2),
        ),
    ]
