# Generated by Django 2.2.6 on 2019-10-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='upper_limit',
        ),
    ]
