# Generated by Django 2.2.6 on 2019-10-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='upper_limit',
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=9),
        ),
    ]
