# Generated by Django 2.2.5 on 2019-09-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('extra_info', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
