# Generated by Django 2.2.5 on 2019-09-27 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='rate_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rates.RateGroup'),
        ),
    ]
