# Generated by Django 2.2.5 on 2019-09-09 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_auto_20190909_0531'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='rate_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rates.RateGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='party_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.PartyCategory'),
        ),
    ]
