# Generated by Django 2.2.5 on 2019-09-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_party_rate_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_wallet_party',
            field=models.BooleanField(default=True),
        ),
    ]
