# Generated by Django 2.2.5 on 2019-09-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_party_is_wallet_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('FL', 'Full Pay'), ('FX', 'Fix Amount Pay')], default='FL', max_length=2),
            preserve_default=False,
        ),
    ]
