# Generated by Django 2.2.5 on 2019-09-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_auto_20190927_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='wallet_type',
        ),
        migrations.AddField(
            model_name='wallet',
            name='deduct_type',
            field=models.CharField(choices=[('FD', 'Full Deduct'), ('FXD', 'Fix Amount Deduct'), ('NFD', 'Non Fixed Amount Deduct')], default='FD', max_length=3),
            preserve_default=False,
        ),
    ]
