# Generated by Django 2.2.5 on 2019-09-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_auto_20190928_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='deduct_type',
            field=models.CharField(choices=[('FD', 'Full Deduct'), ('PD', 'Part Deduct'), ('FXD', 'Fix Deduct')], max_length=3),
        ),
    ]
