# Generated by Django 2.2.5 on 2019-09-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_auto_20190930_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
