# Generated by Django 2.2.5 on 2019-10-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_wallet_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='code',
        ),
        migrations.RemoveField(
            model_name='party',
            name='party_category',
        ),
        migrations.AddField(
            model_name='party',
            name='party_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.DeleteModel(
            name='PartyCategory',
        ),
    ]
