# Generated by Django 2.2.5 on 2019-10-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_auto_20191006_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='is_wallet_party',
            field=models.BooleanField(default=False),
        ),
    ]
