# Generated by Django 2.2.5 on 2019-10-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0009_auto_20191006_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
    ]
