# Generated by Django 2.2.5 on 2019-10-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0010_party_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='rate_type',
            field=models.CharField(choices=[('GR', 'Group Rate'), ('IR', 'Individual Rate')], default='GR', max_length=2),
        ),
    ]
