# Generated by Django 2.2.5 on 2019-10-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0011_party_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='rate_type',
            field=models.CharField(choices=[('GR', 'Group Rate'), ('IR', 'Individual Rate')], max_length=2),
        ),
    ]
