# Generated by Django 2.2.5 on 2019-10-07 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0012_auto_20191006_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='rate_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rates.RateGroup'),
        ),
    ]
