# Generated by Django 2.2.5 on 2019-10-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='has_report',
            field=models.BooleanField(default=False),
        ),
    ]
