# Generated by Django 2.2.7 on 2019-11-05 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='rate_gap',
        ),
        migrations.AddField(
            model_name='material',
            name='down_rate',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(limit_value=0.1)]),
        ),
        migrations.AddField(
            model_name='material',
            name='up_rate',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(limit_value=0.1)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='default_rate',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(limit_value=0.1)]),
        ),
    ]
