# Generated by Django 2.2.6 on 2019-10-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='default_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='material',
            name='rate_gap',
            field=models.FloatField(default=1.0),
        ),
    ]
