# Generated by Django 2.2.6 on 2019-10-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20191015_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='merge_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_materials', to='materials.Material'),
        ),
    ]
