# Generated by Django 2.2.5 on 2019-10-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_has_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='code',
            new_name='material_code',
        ),
    ]
