# Generated by Django 2.2.5 on 2019-10-07 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20191006_2317'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMaterialRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('extra_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material')),
            ],
            options={
                'verbose_name': 'Grouped Material Rate',
                'verbose_name_plural': 'Grouped Material Rates',
            },
        ),
        migrations.AddField(
            model_name='rategroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='MaterialRate',
        ),
        migrations.AddField(
            model_name='groupmaterialrate',
            name='rate_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.RateGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmaterialrate',
            unique_together={('material', 'rate_group')},
        ),
    ]
