# Generated by Django 2.2.5 on 2019-09-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_is_active'),
        ('parties', '0003_auto_20190909_0531'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('extra_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material')),
                ('rate_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.RateGroup')),
            ],
            options={
                'unique_together': {('material', 'rate_group')},
            },
        ),
        migrations.CreateModel(
            name='IndividualRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('extra_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material')),
                ('parties', models.ManyToManyField(to='parties.Party')),
            ],
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
