# Generated by Django 2.2.6 on 2019-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=128)),
                ('acc_no', models.CharField(max_length=32)),
                ('ifsc_code', models.CharField(max_length=32)),
                ('bank_name', models.CharField(max_length=64)),
                ('branch_name', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
