# Generated by Django 2.2.6 on 2019-10-19 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='ifsc_code',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(limit_value=11)]),
        ),
    ]
