# Generated by Django 2.2.6 on 2019-10-18 15:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='amount_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000'), editable=False, max_digits=9),
        ),
    ]
