# Generated by Django 2.2.6 on 2019-10-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_bankaccount_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='branch_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
