# Generated by Django 2.2.5 on 2019-10-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_bankaccount_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='branch_name',
        ),
    ]
