# Generated by Django 2.2.6 on 2019-10-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialstock',
            name='merge_in_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
