# Generated by Django 2.2.6 on 2019-10-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialstock',
            name='in_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialstock',
            name='out_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
