# Generated by Django 2.2.6 on 2019-10-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_materialstock_merge_in_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialstock',
            options={'ordering': ('-date',)},
        ),
    ]
