# Generated by Django 2.2.6 on 2019-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20191022_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstock',
            name='closing_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='materialstock',
            name='in_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='materialstock',
            name='opening_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='materialstock',
            name='out_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
